name: shelly-admin

on:
  push:
    paths:
      - 'shelly-admin/**'
      - '.github/workflows/shelly-admin-release.yml'
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Publish Home Assistant images
        uses: home-assistant/builder@2021.03.4
        with:
          args: |
            --test \
            --all \
            --target /data/shelly-admin
